/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Empresa;

/**
 *
 * @author alexs
 */
public class View extends javax.swing.JFrame {

    Empresa objEmpresa;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPFuncionario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jTFCidade = new javax.swing.JTextField();
        jTFSalario = new javax.swing.JTextField();
        jTFDepartamento = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jBGastos = new javax.swing.JButton();
        jBMedia = new javax.swing.JButton();
        jPEmpresa = new javax.swing.JPanel();
        jTFEmpresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBAdicionarEmpresa = new javax.swing.JButton();
        jPResultado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avaliação Linguagem de Programação II");
        setBackground(new java.awt.Color(255, 255, 255));

        jPFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N
        jPFuncionario.setEnabled(false);

        jLabel2.setText("Matricula");
        jLabel2.setEnabled(false);

        jLabel3.setText("Nome");
        jLabel3.setEnabled(false);

        jLabel4.setText("Cidade");
        jLabel4.setEnabled(false);

        jLabel5.setText("Salario");
        jLabel5.setEnabled(false);

        jLabel6.setText("Departamento");
        jLabel6.setEnabled(false);

        jTFMatricula.setEnabled(false);

        jTFNome.setEnabled(false);

        jTFCidade.setEnabled(false);

        jTFSalario.setEnabled(false);
        jTFSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jTFDepartamento.setEnabled(false);

        jBAdicionar.setText("Adicionar");
        jBAdicionar.setEnabled(false);
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBGastos.setText("Gastos");
        jBGastos.setEnabled(false);
        jBGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGastosActionPerformed(evt);
            }
        });

        jBMedia.setText("Média");
        jBMedia.setEnabled(false);
        jBMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPFuncionarioLayout = new javax.swing.GroupLayout(jPFuncionario);
        jPFuncionario.setLayout(jPFuncionarioLayout);
        jPFuncionarioLayout.setHorizontalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFMatricula)
                    .addComponent(jTFNome)
                    .addComponent(jTFCidade)
                    .addComponent(jTFSalario)
                    .addComponent(jTFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGastos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPFuncionarioLayout.setVerticalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGastos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N

        jLabel1.setText("Empresa");

        jBAdicionarEmpresa.setText("Adicionar");
        jBAdicionarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEmpresaLayout = new javax.swing.GroupLayout(jPEmpresa);
        jPEmpresa.setLayout(jPEmpresaLayout);
        jPEmpresaLayout.setHorizontalGroup(
            jPEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jTFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAdicionarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPEmpresaLayout.setVerticalGroup(
            jPEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpresaLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionarEmpresa)))
        );

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N

        jTAResultado.setEditable(false);
        jTAResultado.setColumns(20);
        jTAResultado.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jTAResultado.setLineWrap(true);
        jTAResultado.setRows(5);
        jTAResultado.setTabSize(4);
        jTAResultado.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPFuncionario.getAccessibleContext().setAccessibleName("Funcionario");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed

        if (jTFMatricula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe a matricula",
                    "Avaliação", 0);
            jTFMatricula.setText(null);
            jTFMatricula.requestFocusInWindow();
            return;

        }
        if (jTFNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe o nome",
                    "Avaliação", 0);
            jTFNome.setText(null);
            jTFNome.requestFocusInWindow();
            return;

        }
        if (jTFCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe a cidade",
                    "Avaliação", 0);
            jTFCidade.setText(null);
            jTFCidade.requestFocusInWindow();
            return;

        }
        if (jTFSalario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe o salário",
                    "Avaliação", 0);
            jTFSalario.setText(null);
            jTFSalario.requestFocusInWindow();
            return;

        }
        if (jTFDepartamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe o departamento",
                    "Avaliação", 0);
            jTFDepartamento.setText(null);
            jTFDepartamento.requestFocusInWindow();
            return;

        }

        String matricula = jTFMatricula.getText();
        String nome = jTFNome.getText();
        String cidade = jTFCidade.getText();
        double salario = Double.parseDouble(jTFSalario.getText());
        String departamento = jTFDepartamento.getText();

        if (objEmpresa.addFuncionario(matricula, nome, cidade, salario, departamento)) {
            JOptionPane.showMessageDialog(null,
                    "Funcionario cadastrado com sucesso",
                    "Avaliação", 1);
            formatarCampos();
            jTAResultado.setText("");
            jTAResultado.append(objEmpresa.toString());
        } else {
            JOptionPane.showMessageDialog(null,
                    "Matricula já cadastrado",
                    "Avaliação", 0);
            jTFMatricula.setEnabled(true);
        }

    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBAdicionarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarEmpresaActionPerformed
        if (jTFEmpresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Informe o nome da empresa",
                    "Avaliação", 0);
            jTFEmpresa.setText(null);
            jTFEmpresa.requestFocusInWindow();
            return;
        }
        String empresa = jTFEmpresa.getText();
        objEmpresa = new Empresa(empresa);
        JOptionPane.showMessageDialog(null,
                "Empresa cadastrada\nInsira os Funcionarios",
                "Avaliação", 1);
        setEnabled();
    }//GEN-LAST:event_jBAdicionarEmpresaActionPerformed

    private void jBGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGastosActionPerformed
        double gastos = objEmpresa.gastosTotais();
        JOptionPane.showMessageDialog(null,
                "No momento o gasto total foi de R$" + gastos,
                "Avaliação", 1);
    }//GEN-LAST:event_jBGastosActionPerformed

    private void jBMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMediaActionPerformed
        double media = objEmpresa.mediaSalarial();
        JOptionPane.showMessageDialog(null,
                "No momento a média salarial foi de R$" + media,
                "Avaliação", 1);
    }//GEN-LAST:event_jBMediaActionPerformed

    private void validaCampo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaCampo
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_validaCampo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    public void setEnabled() {
        jTFMatricula.setEnabled(true);
        jTFNome.setEnabled(true);
        jTFCidade.setEnabled(true);
        jTFSalario.setEnabled(true);
        jTFDepartamento.setEnabled(true);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel6.setEnabled(true);
        jPFuncionario.setEnabled(true);
        jBAdicionar.setEnabled(true);
        jBGastos.setEnabled(true);
        jBMedia.setEnabled(true);
        jPEmpresa.setEnabled(false);
        jLabel1.setEnabled(false);
        jTFEmpresa.setEnabled(false);
        jBAdicionarEmpresa.setEnabled(false);

    }

    public void formatarCampos() {
        jTFMatricula.setText("");
        jTFNome.setText("");
        jTFCidade.setText("");
        jTFSalario.setText("");
        jTFDepartamento.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAdicionarEmpresa;
    private javax.swing.JButton jBGastos;
    private javax.swing.JButton jBMedia;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPEmpresa;
    private javax.swing.JPanel jPFuncionario;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFDepartamento;
    private javax.swing.JTextField jTFEmpresa;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFSalario;
    // End of variables declaration//GEN-END:variables
}
